find_path(MP_INCLUDE_DIRS NAMES muParser/muParser.h muParser.h)

message(${MP_INCLUDE_DIRS})
SET(MP_NAMES ${MP_NAMES} muparser)
MESSAGE(${MP_NAMES})
FIND_LIBRARY(MP_LIBRARIES ${MP_NAMES} )
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(MP DEFAULT_MSG MP_LIBRARIES MP_INCLUDE_DIRS)

MARK_AS_ADVANCED(MP_INCLUDE_DIRS MP_LIBRARIES)

